In [1]:
from pyfem.io.Properties import Properties
from pyfem.assembly.Assembly import Assembly
props = Properties()
props.read_file(r'F:\Github\pyfem\examples\rectangle\rectangle.toml')
assembly = Assembly(props)

assembly.element_data_list[0].material_data.show()

props.materials[0].show()

<function NodeSet.read_gmsh_file at 0x000001F9FF4C9820> running time = 0.003471851348876953 s.
<function ElementSet.read_gmsh_file at 0x000001F9FF4C9CA0> running time = 0.0034720897674560547 s.
<function Assembly.init_element_data_list at 0x000001F9FF7B9D30> running time = 0.013124942779541016 s.
<function Assembly.create_global_stiffness at 0x000001F9FF7B9E50> running time = 0.0014874935150146484 s.
  |- material: <pyfem.io.Material.Material object at 0x000001F9FF7B6EE0>
  |- dimension: 2
  |- option: PlaneStrain
  |- ddsdde: <class 'numpy.ndarray'> with shape = (3, 3) 
     [[120000.  40000.      0.]
      [ 40000. 120000.      0.]
      [     0.      0.  40000.]]
  |- state_variables: <class 'numpy.ndarray'> with shape = (0,) 
     []
  |- name: Material-1
  |- category: Elastic
  |- type: Isotropic
  |- data: [100000.0, 0.25]
